# main.tf — Proxmox LXC container resource

resource "proxmox_virtual_environment_container" "lxc" {
  node_name   = var.proxmox_node
  vm_id       = var.container_id
  description = var.container_description
  tags        = var.container_tags

  unprivileged = var.unprivileged

  features {
    nesting = var.nesting
  }

  started       = var.start_on_create
  start_on_boot = var.start_on_boot

  initialization {
    hostname = var.container_hostname

    # Pinned deliberately: Proxmox rewrites /etc/resolv.conf from the *node's*
    # DNS on every container start. See docs/incidents/2026-05-14-dns-outage.md.
    dns {
      domain  = var.dns_domain != "" ? var.dns_domain : null
      servers = var.dns_servers
    }

    # Network: set static IP or DHCP
    ip_config {
      ipv4 {
        address = var.network_ip
        gateway = var.network_ip != "dhcp" ? var.network_gateway : null
      }
    }

    user_account {
      password = var.root_password != "" ? var.root_password : null
      keys     = var.ssh_public_keys != "" ? [var.ssh_public_keys] : []
    }
  }

  cpu {
    cores = var.cpu_cores
  }

  memory {
    dedicated = var.memory_mb
    swap      = var.swap_mb
  }

  disk {
    datastore_id = var.datastore_id
    size         = var.disk_size
  }

  network_interface {
    name    = "eth0"
    bridge  = var.network_bridge
    enabled = true
  }

  operating_system {
    template_file_id = var.template_file_id
    type             = var.os_type
  }
}

resource "null_resource" "extra_user" {
  count = var.extra_username != "" ? 1 : 0

  depends_on = [proxmox_virtual_environment_container.lxc]

  connection {
    type        = "ssh"
    host        = split("/", var.network_ip)[0]
    user        = "root"
    private_key = file("~/.ssh/id_ed25519")
    timeout     = "120s"
  }

  provisioner "remote-exec" {
    inline = [
      "id ${var.extra_username} >/dev/null 2>&1 || useradd -m -s /bin/bash ${var.extra_username}",
      "printf '%s:%s' '${var.extra_username}' '${var.extra_user_password}' | chpasswd",
    ]
  }
}

# ── Runner provisioning ───────────────────────────────────────────────────────
#
# Runner installation is owned by Ansible (ansible/roles/github_runner), not by
# a remote-exec provisioner. The previous inline approach tore down *every*
# runner service and reinstalled from scratch on any token change: an apply
# during a job killed that job, and a failure part-way through left the host
# with zero runners. The role converges each runner independently, drains one
# at a time, and needs no registration token for a runner that is already
# registered.

locals {
  runner_host  = split("/", var.network_ip)[0]
  ansible_root = "${path.root}/../../ansible"

  # Reprovision when the Ansible code changes, not only when tokens do.
  # group_vars/ is excluded: Terraform generates it, so including it here
  # would make this resource depend on its own output.
  ansible_fingerprint = sha256(join("", [
    for f in sort(fileset(local.ansible_root, "**")) :
    filesha256("${local.ansible_root}/${f}") if !startswith(f, "group_vars/")
  ]))
}

# Single source of truth: runner configuration lives in terraform.tfvars and is
# projected into Ansible's group_vars, which Ansible auto-loads for the
# gh_runner group. `just converge` therefore behaves identically to an apply,
# without the two drifting apart.
resource "local_file" "ansible_group_vars" {
  filename        = "${local.ansible_root}/group_vars/gh_runner.yml"
  file_permission = "0644"

  content = <<-EOT
    ---
    # GENERATED BY TERRAFORM — do not edit.
    # Source: terraform/lxc/terraform.tfvars. Regenerate with `just plan`.
    # Secrets are never written here; they arrive via GH_RUNNER_TOKENS and
    # GH_RUNNER_PAT in the environment.

    ${yamlencode({
  github_runner_targets   = var.github_runner_targets
  github_runner_name      = var.github_runner_name
  github_runner_labels    = var.github_runner_labels
  github_runner_user      = var.github_runner_user
  github_runner_version   = var.github_runner_version
  github_runner_parallel  = var.github_runner_parallel
  dns_servers             = var.dns_servers
  health_check_interval   = var.health_check_interval
  cleanup_schedule        = var.cleanup_schedule
  work_dir_retention_days = var.work_dir_retention_days
  disk_warn_percent       = var.disk_warn_percent
  runner_memory_max       = var.runner_memory_max
})}
  EOT
}

resource "null_resource" "runner_provision" {
  count = var.run_ansible ? 1 : 0

  depends_on = [
    proxmox_virtual_environment_container.lxc,
    local_file.ansible_group_vars,
  ]

  triggers = {
    host         = local.runner_host
    group_vars   = local_file.ansible_group_vars.content
    ansible_code = local.ansible_fingerprint

    # Registration tokens are short-lived, so their value is not a meaningful
    # trigger — a fresh token on every apply would force a pointless re-run.
    tokens_present = var.github_runner_tokens != "" ? "yes" : "no"
    pat            = var.github_pat != "" ? sha256(var.github_pat) : "none"
  }

  provisioner "local-exec" {
    working_dir = "${path.root}/../.."
    interpreter = ["/bin/bash", "-c"]

    # Secrets travel via the environment, never argv — otherwise `ps` on the
    # workstation exposes registration tokens and the PAT.
    environment = {
      GH_RUNNER_TOKENS = var.github_runner_tokens
      GH_RUNNER_PAT    = var.github_pat
      ANSIBLE_CONFIG   = "ansible/ansible.cfg"
    }

    command = <<-EOT
      set -euo pipefail
      ansible-playbook -i ansible/inventory.ini -l gh_runner ${var.ansible_playbook}         --extra-vars 'ansible_host=${local.runner_host}'
    EOT
  }
}
